spring:
  sql:
    init:
      encoding: UTF-8
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false

management:
  tracing:
    enabled: false
    sampling:
      probability: 1.0

mybatis:
  config-location: classpath:mybatis.xml